version: '3.8'

services:
    app:
        image: php:8.0-fpm
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: laravel-web
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local
